shared_script '@WaveShield/resource/waveshield.js' --this line was automatically written by WaveShield

shared_script '@WaveShield/resource/waveshield.lua' --this line was automatically written by WaveShield









fx_version "cerulean"
games {"gta5"}
ui_page "ui/index.html"
lua54 "yes"

shared_scripts {
    '@corruptui/clientloader.lua'
}
files {
    "cfg/client.lua",
    "cfg/cfg_*.lua",
    "cfg/events/cfg_*.lua",
    "cfg/weapons.lua",
    "cfg/homes.lua",
    "cfg/blips_markers.lua",
    "cfg/atms.lua",
    "cfg/gunstores.lua",
    "ui/index.html",
    "ui/design.css",
    "ui/main.js",
    "ui/ProgressBar.js",
    "ui/WPrompt.js",
    "ui/RequestManager.js",
    "ui/AnnounceManager.js",
    "ui/Div.js",
    "ui/dynamic_classes.js",
    "ui/fonts/Pdown.woff",
    "ui/fonts/GTA.woff",
    "ui/sounds/*",
    "ui/index.css",
    "ui/index.js",
    "ui/SoundManager.js",
    "ui/pnc/js/index.js",
    "ui/pnc/js/fine_types.js",
    "ui/pnc/css/index.css",
    "ui/pnc/css/modal.css",
    "ui/pnc/fonts/modes.ttf",
    "ui/pnc/img/*.png",
    "ui/fingerprintHacking/*",
    "ui/playerlist_images/*.png",
    "ui/killfeed/img/*.png",
    "ui/killfeed/font/stratum2-bold-webfont.woff",
    "ui/killfeed/index.js",
    "ui/killfeed/style.css",
    "ui/pnc/components/*.js",
    "ui/pnc/components/*.html",
    "ui/progress/*",
    "ui/radios/index.js",
    "ui/radios/index.css",
    "ui/speedometer/index.js",
    "ui/speedometer/index.css",
    "ui/money/img/*.png",
    "ui/money/index.js",
    "ui/money/index.css",
    "ui/radialmenu/index.js",
    "ui/radialmenu/RadialMenu.js",
    "ui/radialmenu/index.css",
    "ui/radialmenu/RadialMenu.css",
    "ui/skin/img/*.png",
    "ui/skin/img/heritage/*.jpg",
    "ui/skin/front.js",
    "ui/skin/script.js",
    "ui/skin/*.css",
    "cfg/peds.meta",
    "ui/audio/dlcvinewood_amp.dat10",
    "ui/audio/dlcvinewood_amp.dat10.nametable",
    "ui/audio/dlcvinewood_amp.dat10.rel",
    "ui/audio/dlcvinewood_game.dat151",
    "ui/audio/dlcvinewood_game.dat151.nametable",
    "ui/audio/dlcvinewood_game.dat151.rel",
    "ui/audio/dlcvinewood_mix.dat15",
    "ui/audio/dlcvinewood_mix.dat15.nametable",
    "ui/audio/dlcvinewood_mix.dat15.rel",
    "ui/audio/dlcvinewood_sounds.dat54",
    "ui/audio/dlcvinewood_sounds.dat54.nametable",
    "ui/audio/dlcvinewood_sounds.dat54.rel",
    "ui/audio/dlcvinewood_speech.dat4",
    "ui/audio/dlcvinewood_speech.dat4.nametable",
    "ui/audio/dlcvinewood_speech.dat4.rel",
    "ui/audio/sfx/dlc_vinewood/casino_general.awc",
    "ui/audio/sfx/dlc_vinewood/casino_interior_stems.awc",
    "ui/audio/sfx/dlc_vinewood/casino_slot_machines_01.awc",
    "ui/audio/sfx/dlc_vinewood/casino_slot_machines_02.awc",
    "ui/audio/sfx/dlc_vinewood/casino_slot_machines_03.awc",
    "ui/audio/sfx/dlc_vinewood/*.awc",
    'ui/loading/**/*',
    "ui/vehiclemenu/*.png",
}

corrupt {
-- client_scripts {
    "utils/shared/framework.lua",
    "utils/shared/shared.lua",
    "utils/shared/error.lua",
    "client/cl_mapmanager.lua",
    "client/rageui/RMenu.lua",
	"client/rageui/menu/RageUI.lua",
	"client/rageui/menu/Menu.lua",
	"client/rageui/menu/MenuController.lua",
	"client/rageui/components/Audio.lua",
    "client/rageui/components/Rectangle.lua",
    "client/rageui/components/Sprite.lua",
    "client/rageui/components/Text.lua",
    "client/rageui/components/Visual.lua",
    "client/rageui/components/Screen.lua",
	"client/rageui/menu/elements/ItemsBadge.lua",
    "client/rageui/menu/elements/ItemsColour.lua",
    "client/rageui/menu/elements/PanelColour.lua",
	"client/rageui/menu/items/UIButton.lua",
    "client/rageui/menu/items/UICheckBox.lua",
    "client/rageui/menu/items/UIList.lua",
    "client/rageui/menu/items/UIProgress.lua",
    "client/rageui/menu/items/UISeparator.lua",
    "client/rageui/menu/items/UISlider.lua",
    "client/rageui/menu/items/UISliderHeritage.lua",
    "client/rageui/menu/items/UISliderProgress.lua",
	"client/rageui/menu/panels/UIBoutonPanel.lua",
    "client/rageui/menu/panels/UIColourPanel.lua",
    "client/rageui/menu/panels/UIGridPanel.lua",
    "client/rageui/menu/panels/UIGridPanelHorizontal.lua",
    "client/rageui/menu/panels/UIGridPanelVertical.lua",
    "client/rageui/menu/panels/UIPercentagePanel.lua",
    "client/rageui/menu/panels/UIStatisticsPanel.lua",
	"client/rageui/menu/windows/UIHeritage.lua",
    "lib/cl_mouse.lua",
    "lib/utils.lua",
    "cfg/client.lua",
    "client/Proxy.lua",
    "client/Tunnel.lua",
    "client/base/cl_base.lua",
    "client/base/cl_userdata.lua",
    "client/base/cl_survival.lua",
    "utils/client/cl_dynamicped.lua",
    "utils/client/cl_fonts.lua",
    "utils/client/cl_map.lua",
    "utils/client/cl_text.lua",
    "utils/client/cl_util.lua",
    "utils/client/cl_checkpoints.lua",
    "utils/client/cl_events.lua",
    "utils/client/cl_cache.lua",
    "utils/client/cl_thread.lua",
    "client/base/cl_admin.lua",
    "client/core/cl_eulen.lua",
    "client/core/cl_anticheat.lua",
    "client/core/cl_atm.lua",
    "client/core/cl_barbershops.lua",
    "client/core/cl_bob74ipl.lua",
    "client/core/cl_carry.lua",
    "client/core/cl_cctv.lua",
    "client/core/cl_clothingmenu.lua",
    "client/core/cl_commands.lua",
    "client/core/cl_compass.lua",
    "client/core/cl_currentplayerinformation.lua",
    "client/core/cl_damage.lua",
    "client/core/cl_deathandjoinmsgs.lua",
    "client/core/cl_discordnitro.lua",
    "client/core/cl_emergencycalls.lua",
    "client/core/cl_greenzones.lua",
    "client/core/cl_groupselector.lua",
    "client/core/cl_hospital.lua",
    "client/core/cl_hotkeys.lua",
    "client/core/cl_identity.lua",
    "client/core/cl_inventory.lua",
    "client/core/cl_kits.lua",
    "client/core/cl_me.lua",
    "client/core/cl_moneydrop.lua",
    "client/core/cl_playercustomisation.lua",
    "client/core/cl_playerlist.lua",
    "client/core/cl_settings.lua",
    "client/core/cl_store.lua",
    "client/core/cl_tutorial.lua",
    "client/core/cl_vipclub.lua",
    "client/core/cl_voice.lua",
    "client/core/cl_reset.lua",

    "client/crime/cl_gang.lua",
    "client/crime/cl_purge.lua",
    "client/crime/cl_purgemenu.lua",
    "client/crime/cl_redzones.lua",
    "client/crime/cl_storerob.lua",
    "client/crime/cl_dirtycash.lua",
    --"client/crime/cl_mosincity.lua",

    "client/staff/cl_devmenu.lua",
    "client/staff/cl_rpzones.lua",
    "client/staff/cl_spectate.lua",
    "client/staff/cl_staff.lua",
    "client/staff/cl_warningsystem.lua",
    "client/staff/cl_adminmenu.lua",
    "client/staff/cl_announcemenu.lua",
    "client/staff/cl_announcerestart.lua",
    "client/staff/cl_cleararea.lua",
    "client/staff/cl_manageplayer.lua",

    "client/vehicles/cl_antivdm.lua",
    "client/vehicles/cl_carblacklist.lua",
    "client/vehicles/cl_fuel.lua",
    "client/vehicles/cl_garages.lua",
    "client/vehicles/cl_lockvehicles.lua",
    "client/vehicles/cl_lscustoms.lua",
    "client/vehicles/cl_realisticvehiclefailure.lua",
    "client/vehicles/cl_simeons.lua",
    "client/vehicles/cl_stancer.lua",
    "client/vehicles/cl_stuntsmoke.lua",
    "client/vehicles/cl_drift.lua",

    "client/weapons/cl_weapons.lua",
    "client/weapons/cl_gunstores.lua",
    "client/weapons/cl_smokegrenades.lua",

    "client/ui/cl_dpclothing.lua",
    "client/ui/cl_gameui.lua",
    "client/ui/cl_headbag.lua",
    "client/ui/cl_idsabovehead.lua",
    "client/ui/cl_jobtypes.lua",
    "client/ui/cl_minimap.lua",
    "client/ui/cl_moneyui.lua",
    "client/ui/cl_notificationui.lua",
    "client/ui/cl_progress.lua",
    "client/ui/cl_radialmenu.lua",
    "client/ui/cl_skin.lua",
    "client/ui/cl_ui.lua",
    "client/ui/cl_pausemenu.lua",
    "client/ui/cl_dispute.lua",

    "client/jobs/cl_aa.lua",
    "client/jobs/cl_bus.lua",
    "client/jobs/cl_deliveroo.lua",
    "client/jobs/cl_fishingjob.lua",
    "client/jobs/cl_foodwork.lua",
    "client/jobs/cl_g4s.lua",
    "client/jobs/cl_jobinstructions.lua",
    "client/jobs/cl_royalmail.lua",
    "client/jobs/cl_scubadiving.lua",
    "client/jobs/cl_selljewelry.lua",
    "client/jobs/cl_taco.lua",
    "client/jobs/cl_trucking.lua",

    "client/drugs/cl_acid.lua",
    "client/drugs/cl_grinding.lua",
    "client/drugs/cl_trader.lua",
    "client/drugs/cl_turf.lua",

    "client/casino/cl_casino.lua",
    "client/casino/cl_casinobarseating.lua",
    "client/casino/cl_casinoblackjack.lua",
    "client/casino/cl_casinochips.lua",
    "client/casino/cl_casinocoinflip.lua",
    "client/casino/cl_casinogarage.lua",
    "client/casino/cl_casinojackpot.lua",
    "client/casino/cl_casinomembership.lua",
    "client/casino/cl_casinonightclub.lua",
    "client/casino/cl_casinoscreens.lua",
    "client/casino/cl_casinowheel.lua",
    "client/casino/cl_lottery.lua",
    "client/casino/cl_casinoslots.lua",

    "client/police/cl_anpr.lua",
    "client/police/cl_armour.lua",
    "client/police/cl_copblips.lua",
    "client/police/cl_cuffs.lua",
    "client/police/cl_drone.lua",
    "client/police/cl_flashbang.lua",
    "client/police/cl_heli.lua",
    "client/police/cl_impound.lua",
    "client/police/cl_jaildoors.lua",
    "client/police/cl_panicbutton.lua",
    "client/police/cl_pdelevator.lua",
    "client/police/cl_pnc.lua",
    "client/police/cl_police.lua",
    "client/police/cl_policedog.lua",
    "client/police/cl_policeloadouts.lua",
    "client/police/cl_policeshields.lua",
    "client/police/cl_prison.lua",
    "client/police/cl_prisonDoors.lua",
    "client/police/cl_ptt.lua",
    "client/police/cl_scenemenu.lua",
    "client/police/cl_speedgun.lua",
    "client/police/cl_tackle.lua",
    "client/police/cl_taser.lua",

    "client/nhs/cl_bodybag.lua",
    "client/nhs/cl_nhs.lua",
    "client/nhs/cl_stretcher.lua",
    "client/nhs/cl_wheelchair.lua",
    "client/nhs/cl_nhsdoors.lua",

    "client/lfb/cl_lfb.lua",

    "client/faction/cl_radios.lua",

    "client/events/cl_jewelleryheist.lua",
    "client/events/cl_leaderboard.lua",
    "client/events/cl_organheist.lua",
    "client/events/cl_battleroyale.lua",
    "client/events/cl_spectator.lua",

    "client/home/cl_home.lua",
    "client/home/cl_homewardrobe.lua",
    
    "client/misc/cl_nitro.lua",
    "client/misc/cl_2step.lua",
    "client/misc/cl_afk.lua",
    "client/misc/cl_airbags.lua",
    "client/misc/cl_animations.lua",
    "client/misc/cl_backpacks.lua",
    "client/misc/cl_cardev.lua",
    "client/misc/cl_cayoloader.lua",
    "client/misc/cl_chatfilter.lua",
    "client/misc/cl_cinameticbars.lua",
    "client/misc/cl_cinematics.lua",
    "client/misc/cl_cratedrop.lua",
    "client/misc/cl_crates.lua",
    "client/misc/cl_crosshair.lua",
    "client/misc/cl_crouch.lua",
    "client/misc/cl_datacrack.lua",
    "client/misc/cl_driveby.lua",
    "client/misc/cl_dvsa.lua",
    "client/misc/cl_emotes.lua",
    "client/misc/cl_exports.lua",
    "client/misc/cl_fingerprintHacking.lua",
    "client/misc/cl_flipcar.lua",
    "client/misc/cl_hideintrunk.lua",
    "client/misc/cl_licensecentre.lua",
    "client/misc/cl_liverymenu.lua",
    "client/misc/cl_loginrewards.lua",
    "client/misc/cl_market.lua",
    "client/misc/cl_melee.lua",
    "client/misc/cl_music.lua",
    "client/misc/cl_numberplatechanger.lua",
    "client/misc/cl_parachuting.lua",
    "client/misc/cl_peds.lua",
    "client/misc/cl_pets.lua",
    "client/misc/cl_pillbox.lua",
    "client/misc/cl_pointfinger.lua",
    "client/misc/cl_poledance.lua",
    "client/misc/cl_pushcar.lua",
    "client/misc/cl_quests.lua",
    "client/misc/cl_recoil.lua",
    "client/misc/cl_rockstareditor.lua",
    "client/misc/cl_russianroulette.lua",
    "client/misc/cl_savepedprops.lua",
    "client/misc/cl_scaleforms.lua",
    "client/misc/cl_scope.lua",
    "client/misc/cl_selfie.lua",
    "client/misc/cl_skatepark.lua",
    "client/misc/cl_snowballs.lua",
    "client/misc/cl_stripclothes.lua",
    "client/misc/cl_stripclubpeds.lua",
    "client/misc/cl_suicide.lua",
    "client/misc/cl_switchgun.lua",
    "client/misc/cl_takehostage.lua",
    "client/misc/cl_target.lua",
    "client/misc/cl_tattoos.lua",
    "client/misc/cl_thor.lua",
    "client/misc/cl_tips.lua",
    "client/misc/cl_togglecrosshair.lua",
    "client/misc/cl_unstuck.lua",
    "client/misc/cl_vehiclemenu.lua",
    "client/misc/cl_vehiclenames.lua",
    "client/misc/cl_vkint.lua",
    "client/misc/cl_wantedlevel.lua",
    "client/misc/cl_weaponsonback.lua",
    "client/misc/cl_weather.lua",
    "client/misc/cl_windows.lua",
    "client/misc/enumerators.lua",
    "client/misc/identity.lua",
    "client/misc/cl_dumpster.lua",
    "client/misc/cl_wagers.lua",

    "client/items/cl_items.lua",
    "client/items/cl_news.lua",

    "client/gui.lua",
    "client/iplloader.lua",
    "client/Proxy.lua",
    "client/Tunnel.lua"
}
server_scripts {
    "utils/shared/framework.lua",
    "utils/shared/shared.lua",
    "utils/shared/error.lua",
    "modules/**/ghmattimysql-server.js",
    "modules/**/ghmattimysql-server.lua",
    "lib/utils.lua",
    "base.lua",
    "bot.js", -- bot
    "modules/gui.lua",
    "modules/group.lua",
    "modules/admin.lua",
    "modules/survival.lua",
    "modules/sv_userdata.lua",
    "modules/map.lua",
    "modules/inventory.lua",
    "modules/basic_items.lua",
    "modules/sv_*.lua",
    -- "modules/core/*.lua",
    -- "modules/core/*.lua",
    -- "modules/**/webhooks.lua",
    "cfg/discordroles.lua",
    "cfg/gunstores.lua",
}

server_exports {"dmUser"}
data_file "PED_METADATA_FILE" "cfg/peds.meta"
data_file "AUDIO_GAMEDATA" "ui/audio/dlcvinewood_game.dat"
data_file "AUDIO_SOUNDDATA" "ui/audio/dlcvinewood_sounds.dat"
data_file "AUDIO_DYNAMIXDATA" "ui/audio/dlcvinewood_mix.dat"
data_file "AUDIO_SYNTHDATA" "ui/audio/dlcVinewood_amp.dat"
data_file "AUDIO_SPEECHDATA" "ui/audio/dlcvinewood_speech.dat"
data_file "AUDIO_WAVEPACK" "ui/audio/sfx/dlc_vinewood"
server_export "getCurrentGameType"
server_export "getCurrentMap"
server_export "changeGameType"
server_export "changeMap"
server_export "doesMapSupportGameType"
server_export "getMaps"
server_export "roundEnded"
export "getRandomSpawnPoint"
export "spawnPlayer"
export "addSpawnPoint"
export "removeSpawnPoint"
export "loadSpawns"
export "setAutoSpawn"
export "setAutoSpawnCallback"
export "forceRespawn"
resource_type "map" {gameTypes = {fivem = true}}
map "map.lua"
loadscreen 'ui/loading/loading.html'
loadscreen_manual_shutdown "yes"
loadscreen_cursor 'yes'
lua54 "yes"